### ISSUE TITLE
zjs-servers temperature.js and multiserver.js don't work with Zephyr SDK 0.9.1

### ISSUE THREAD

**Issue by qiuzhong** [01org/SmartHome-Demo#149]
After upgrading to [Zephyr SDK 0.9.1](https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases/download/0.9.1/zephyr-sdk-0.9.1-setup.run), the zjs-servers [temperature.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/temperature.js) and [multiserver.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/multiserver.js) don't work any more: The "ZJS Device" cannot be discovered via a Bluetooth client app or the <code>bluetoothctl</code> utility on Linux. So the 6LoWPAN cannot be set up.

[led.js](https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/led.js) can still work well with Zephyr SDK 0.9.1, though.

All the zjs-servers can work well with [Zephyr SDK 0.9](https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases/download/0.9/zephyr-sdk-0.9-setup.run).

**Comment by qiuzhong** [comment]
Is this the same as [zephyr.js issue#1204](https://github.com/01org/zephyr.js/issues/1204)?

**Comment by qiuzhong** [comment]
@ttzeng

**Comment by ttzeng** [comment]
@qiuzhong , yes, this is caused by the upstream bug #1204. Thank you for linking them!

**Comment by uhofemei** [comment]
I was able to observe temperature based on PR https://github.com/01org/SmartHome-Demo/pull/150.

**Comment by qiuzhong** [comment]
Tested PR #150 with Zephyr SDK v0.9.1 and it turned out that `multiservers2.js` can work with Zephyr SDK v0.9.1.

**Comment by ttzeng** [comment]
Per the [upstream report of issue #1204](https://github.com/01org/zephyr.js/issues/1204), it seems the SDK 0.9.1 breaks at least the ADC and the on-chip BMI160 peripherals (i.e. temperature, gyro, accelerometer). The temperature resource in [PR#139](https://github.com/01org/SmartHome-Demo/pull/139) drives the on-chip BMI, which is impacted. The temperature resource in [PR#150](https://github.com/01org/SmartHome-Demo/pull/150) drives an external TH02 sensor on the I2C bus, which works fine.

**Comment by gvancuts** [comment]
The initial description makes it look like there is a problem with the Bluetooth part as well as with some sensors (such as the integrated BMI160). Based on the latest comments however, it seems like the Bluetooth part is actually fine and it's just _some_ sensors that are affected. Is that correct?

One important question related to this: when we are testing a new SDK such as 0.9.1, are we building and flashing **all three** binaries (i.e. `hci_uart`, `arc` and `x86`)?

**Comment by qiuzhong** [comment]
I didn't build and flash the `hci_uart` when I filed this issue.

The [Zephyr.js](https://github.com/01org/zephyr.js) QA had confirmed that with Zephyr SDK v0.9.1, the [BLE.js](https://github.com/01org/zephyr.js/blob/master/samples/BLE.js) (It tests BLE function only) still works fine. But if you use both the impacted sensors and BLE function, the Bluetooth network will not be set up and be discovered.

@gvancuts , you're right. Only some sensors are affected by Zephyr SDK v0.9.1.

**Comment by qiuzhong** [comment]
I just updated the `hci_uart` binary built with Zephyr SDK v0.9.1 and tried again. It didn't help.

**Comment by ttzeng** [comment]
The issue is Arduino 101 won't be able to boot if build against the SDK 0.9.1
PS: "ipm_console0: 'Sensor core running ZJS ARC support image" message is expected to be shown on the serial console; however, no any messages shown while using SDK 0.9.1

**Comment by gvancuts** [comment]
Could we summarize what works with the various Zephyr SDKs? For example:

| Zephyr SDK | BLE | sensors |
| --- | --- | --- |
| 0.8.2 | OK | OK |
| 0.9.0 | NOK | OK |
| 0.9.1 | OK | NOK * |

*: only some sensors are not working as expected, more specifically the BMI160 and (any other?)

Is that right?

**Comment by uhofemei** [comment]
IMHO we should not report the temperature from the BMI160, but an external grove temperature sensor instead. The internal MCU reading reports 20+ Celsius more than the actual outside temperature and we currently don't indicate that the temperature reading is the internal MCU temperature and not the outside temperature value.

**Comment by qiuzhong** [comment]
@gvancuts , here is the summary of different SDK versions:

| Zephyr SDK	| BLE | Sensor |
| --- | --- | --- |
| 0.8.2 | OK | OK |
| 0.9 | OK | OK |
| 0.9.1 | OK | NOK* |

*: only some sensors are not working as expected, more specifically the BMI160 and Grove light sensor.

**Comment by gvancuts** [comment]
Thanks @qiuzhong .

@kiendinh , there was something about the Zephyr SDK 0.9.0 that did not work, at least when using native code... I thought it was related to Bluetooth but apparently not, can you refresh my memory as to what that was? Thanks!

**Comment by kiendinh** [comment]
@gvancuts : it's something relating to compiler bugs with -Os. Here is the bug: 
https://jira.zephyrproject.org/browse/ZEP-1882

They got it fixed by upgrading to gcc 6.3.0.

**Comment by gvancuts** [comment]
Thanks @kiendinh . Did they fix that in 0.9.0 or 0.9.1?

I am still confused since reading through https://github.com/01org/zephyr.js/issues/1204 made me believe the ADC is still broken in 0.9.1.

Is there an OCF server in our ZJS sample portfolio that **requires** ADC? If so, which version of the SDK does it work with?

**Comment by qiuzhong** [comment]
**Update**: Zephyr SDK 0.9.1 can work with the example now (with zephyr.js commit [ddc30dc](https://github.com/01org/zephyr.js/commit/ddc30dc9db3963977eac933be148ffc54c23aec2)). Can we close this issue now?

**Comment by ttzeng** [comment]
+1   the SDK 0.9.1 is required, or the build will abort and ask the user to use SDK 0.9.1

**Comment by gvancuts** [comment]
Great!

@ttzeng , are you saying that the build system will automatically abort of 0.9.1 is not installed?

Do we need to update this paragraph [1] to keep our documentation up to date?
[1] https://github.com/01org/SmartHome-Demo/blob/master/ocf-servers/zjs-servers/README.md#setup-zjs-build-environment

Thanks!

**Comment by ttzeng** [comment]
@gvancuts yes, the Zephyr dependency in ZJS will check the toolchain version, it won't build if SDK 0.9.1 is not installed, and this already highlighted in the README.md of our ZJS samples in the PR#170.

**Comment by gvancuts** [comment]
Thanks @ttzeng!

Shouldn't we update the README.md to advice people to use this newer commit (https://github.com/01org/zephyr.js/commit/ddc30dc9db3963977eac933be148ffc54c23aec2) as opposed to the one currently referenced (whic is older: (https://github.com/01org/zephyr.js/commit/55e8293ac516c74d072cf84ea6910643b626c924))?

**Comment by ttzeng** [comment]
> ...(b) checkout the **commit with the latest API** we have validated...

@gvancuts the original idea is to highlight **the commit of API** instead of the commit we've validated, to avoid updating the link in this README.md every time when ZJS push to a new HEAD. Anyway, proposing to rephrase as "(b) checkout the **known-to-work** commit which we have validated" in the PR #173

**Comment by qiuzhong** [comment]
Close it as upstream fixed.

**Comment by gvancuts** [comment]
Hi @ttzeng , are you saying that https://github.com/01org/zephyr.js/commit/55e8293ac516c74d072cf84ea6910643b626c924 as currently indicated in the dco _should_ work? If so, I'm fine with leaving the doc as is, I thought that using a newer commit ID was *required* for things to work correctly. If not, please disregard my request.
